"""remove subscription

Revision ID: 17485872fff7
Revises: 
Create Date: 2020-09-08 21:47:26.720746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17485872fff7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'subscription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subscription', mysql.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
