"""added review

Revision ID: 465ef2d21d9a
Revises: 67a74c9a5459
Create Date: 2020-11-26 17:58:54.590235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465ef2d21d9a'
down_revision = '67a74c9a5459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###
